server.port=8080
prometheus.url=${PROMETHEUS_URL:http://localhost:9091}
prometheus.username=${PROMETHEUS_USERNAME:}
prometheus.password=${PROMETHEUS_PASSWORD:}
prometheus.bearer-token=${PROMETHEUS_BEARER_TOKEN:}
